name: VoteCoins
version: 1.0
author: Lactem
main: com.minecave.votecoins.Main
depend: [Votifier]
commands:
  votecoin:
    aliases: [votecoins, vc]
  vcshop:
    aliases: [votecoinshop, coinshop]
  rewards:
    aliases: []
  vote:
    aliases: []
  votetop:
    aliases: [vtop]