name: VoteCoins
version: 1.0
author: Lactem
main: com.minecave.votecoins.Main
depend: [Votifier]
commands:
  votecoin:
    description: Check how many coins you have.
    aliases: [votecoins, vc]
  vcshop:
    description: Open the coin shop.
  rewards:
    description: Lists the possible rewards from voting.
    aliases: reward
  vote:
    description: Lists voting links.
    aliases: voting
  votetop:
    description: Lists the top voters.
    aliases: topvoters
  coinaddvotelistener:
    description: Adds a vote listener.